apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gather-omdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gather-omdb
    spec:
      containers:
      - name: gather-omdb
        image: localhost:5000/kino/gather-omdb:latest