FROM python:3.6-slim

ARG KAFKA_BROKER
ARG OMDB_API_KEY
ARG TMDB_API_KEY
ARG YOUTUBE_API_KEY
ARG DB_SERVER
ARG DB_PORT
ARG DB_DATABASE
ARG DB_USER
ARG DB_PASSWORD

ENV KAFKA_BROKER $KAFKA_BROKER
ENV OMDB_API_KEY $OMDB_API_KEY
ENV TMDB_API_KEY $TMDB_API_KEY
ENV YOUTUBE_API_KEY $YOUTUBE_API_KEY
ENV DB_SERVER $DB_SERVER
ENV DB_PORT $DB_PORT
ENV DB_DATABASE $DB_DATABASE
ENV DB_USER $DB_USER
ENV DB_PASSWORD $DB_PASSWORD

COPY  . /code
WORKDIR /code

RUN pip3 install -r requirements.txt

CMD ["python3", "kafka_actor.py"]