apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: get-amazon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-amazon
  template:
    metadata:
      labels:
        app: get-amazon
    spec:
      containers:
      - name: get-amazon
        image: kinoreel/gather:latest
        imagePullPolicy: Always
        env:
          - name: PROCESS
            value: "get_amazon"
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: kafka_broker
          - name: AWS_API_KEY
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: aws_api_key