apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: get-itunes
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: get-itunes
    spec:
      containers:
      - name: get-itunes
        image: kinoreel/gather:latest
        imagePullPolicy: Always
        env:
          - name: PROCESS
            value: "get_itunes"
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: kafka_broker