apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: gather-omdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: get-omdb
    spec:
      containers:
      - name: get-omdb
        image: kinoreel/gather:latest
        env:
          - name: PROCESS
            value: "get_omdb"
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: kafka_broker
          - name: OMDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: omdb_api_key