apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: get-tmdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-tmdb
  template:
    metadata:
      labels:
        app: get-tmdb
    spec:
      containers:
      - name: get-tmdb
        image: kinoreel/gather:latest
        imagePullPolicy: Always
        env:
          - name: PROCESS
            value: "get_tmdb"
          - name: KAFKA_BROKER
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: kafka_broker
          - name: TMDB_API_KEY
            valueFrom:
              secretKeyRef:
                name: kino-secrets
                key: tmdb_api_key