apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: insert-person-roles
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: insert-person-roles
    spec:
      containers:
      - name: insert-person-roles
        image: eu.gcr.io/kino-173106/insert-personroles:latest